name: Makefile CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt-get update -y
                sudo apt-get install -y --no-install-recommends libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev gettext

            - name: Install LLVM
              run: |
                wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
                sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-19 main"
                sudo apt-get update -y
                sudo apt-get install -y --no-install-recommends llvm-19-dev

            - name: Build project
              run: |
                git submodule init
                git submodule update
                make CC=gcc-9 USE_COMPILER=TRUE LLVM_CONFIG=llvm-config-19
